modLoader="javafml"
loaderVersion="[1.0.0,)"
license="MIT"
issueTrackerURL="https://github.com/LegendarySpy/Biome-Replacer-Neoforge/issues"

[[mods]]
modId="biome_replacer"
version="1.2.1"
displayName="Biome Replacer" #mandatory
updateJSONURL="https://api.modrinth.com/updates/biome-replacer-neoforge/forge_updates.json"
displayURL="https://modrinth.com/mod/biome-replacer-neoforge"
logoFile="icon.png"
authors="LegendarySpy"
displayTest="IGNORE_SERVER_VERSION"
description='''This mod replaces biomes in Minecraft with new ones.'''

[[dependencies.biome_replacer]]
modId="forge"
mandatory=true
versionRange="[47.0.0,)"
ordering="NONE"
side="SERVER"

[[dependencies.biome_replacer]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="SERVER"