
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://WerDei/Biome-Replacer-Forge/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}" #mandatory
updateJSONURL="https://api.modrinth.com/updates/biome-replacer/forge_updates.json"
displayURL="https://modrinth.com/mod/biome-replacer"
logoFile="icon.png"
authors="${mod_authors}"
displayTest="IGNORE_SERVER_VERSION"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
   modId="forge"
   mandatory=true
   versionRange="${forge_version_range}"
   ordering="NONE"
   side="SERVER"

[[dependencies.${mod_id}]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="SERVER"
